### ISSUE TITLE
Error in script whan try to audit a wifi network

### ISSUE THREAD

**Issue by peterpt** [SYWorks/waidps#3]
I get an error when i try to audit a network , this is started to happen when i updated waidps to latest repository on github , previous version did not had this issue 

[i]   Below are the list of collected WEP/WPA/WPA2 network with information of WPS enabled router and number associated clients.

Traceback (most recent call last):
  File "./waidps.py", line 18755, in <module>
    Main()
  File "./waidps.py", line 15301, in Main
    retkey=WaitingCommands(**builtin**.TIMEOUT,1)
  File "./waidps.py", line 5657, in WaitingCommands
    RR=GetOptionCommands("1")
  File "./waidps.py", line 5552, in GetOptionCommands
    OptAuditing("")
  File "./waidps.py", line 566, in OptAuditing
    **builtin**.TargetList_WEP=[];**builtin**.TargetList_WPA1=[];**builtin**.TargetList_WPA2=[];**builtin**.TargetList_WPA1C=[];**builtin**.TargetList_WPA2C=[];**builtin**.TargetList_WPS=[]; builtin__.TargetList_All=[];**builtin**.CUR_CLIENT=[]
NameError: global name 'builtin__' is not defined

a print screen image of the error can be found in postimg link above
http://s7.postimg.org/r9u6n8nez/waidpserror.png

**Comment by SYWorks** [comment]
sorry pal.. have been busy recently..
thanks for raising up this problem.. it seem that the "**builtin**" function have been truncated during the uploading.. anyway i have uploaded the new fixed problem. 
Thanks again. :)

**Comment by peterpt** [comment]
no problem ;)
thanks , it is working perfectly now .
